"""Propose alias entries from An API of Ice and Fire.

Run by hand, not by the build:

    python -m pipeline.tools.propose_aliases

Writes a suggestion file next to the real alias table. It never edits the table
itself, because the whole point of a hand-maintained table is that a human
decided what is in it — an inferred mapping that silently splits or merges a
character corrupts every signature downstream and does so quietly.

Source: <https://anapioficeandfire.com>, maintained by Joakim Skoog. The service
is free and unauthenticated (20,000 requests per IP per day). Alias lists are
facts about naming rather than creative expression, so they carry no licence of
their own, but the API is credited in the generated file regardless.
"""

from __future__ import annotations

import json
import time
import urllib.request
from pathlib import Path

from ..ingest.asoiaf import load

API = "https://anapioficeandfire.com/api/characters"
CACHE = Path(__file__).resolve().parent.parent / "raw" / "asoiaf" / "anapioficeandfire-characters.json"
OUT = Path(__file__).resolve().parent.parent / "aliases" / "asoiaf.suggested.yaml"

# A player types a nickname, not a full honorific. "Lord Snow" is worth having in
# the type-ahead; "The 998th Lord Commander of the Night's Watch" is not.
MAX_ALIAS_WORDS = 4

USER_AGENT = "YouAreHere-pipeline/0.1 (+https://github.com/; alias table first pass)"


def fetch(page_size: int = 50) -> list[dict]:
    if CACHE.exists():
        return json.loads(CACHE.read_text(encoding="utf-8"))

    characters, page = [], 1
    while True:
        url = f"{API}?page={page}&pageSize={page_size}"
        # The service rejects the default urllib agent with a 403.
        request = urllib.request.Request(url, headers={"User-Agent": USER_AGENT})
        with urllib.request.urlopen(request, timeout=30) as response:
            batch = json.loads(response.read().decode("utf-8"))
        if not batch:
            break
        characters.extend(batch)
        print(f"  page {page:>3}  {len(characters):>5} characters")
        page += 1
        time.sleep(0.1)

    CACHE.parent.mkdir(parents=True, exist_ok=True)
    CACHE.write_text(json.dumps(characters, ensure_ascii=False, indent=1), encoding="utf-8")
    return characters


def main() -> int:
    print("fetching An API of Ice and Fire ...")
    characters = fetch()
    print(f"  {len(characters)} characters available\n")

    by_name: dict[str, dict] = {}
    for character in characters:
        if character["name"]:
            by_name.setdefault(character["name"].lower(), character)

    graph = load()

    # Matching on display name alone merges distinct people: the graph holds two
    # characters called "Aemon Targaryen", and a name lookup hands both of them
    # the Maester's aliases. Anything whose name is not unique gets flagged so a
    # reviewer sees it rather than pasting it in.
    name_counts: dict[str, int] = {}
    for node in graph.nodes:
        name_counts[node.name.lower()] = name_counts.get(node.name.lower(), 0) + 1

    matched, unmatched, proposals = 0, [], {}

    for node in graph.nodes:
        character = by_name.get(node.name.lower())
        if not character:
            unmatched.append(node.name)
            continue
        matched += 1
        aliases = [
            alias for alias in character["aliases"]
            if alias and len(alias.split()) <= MAX_ALIAS_WORDS and alias.lower() != node.name.lower()
        ]
        if aliases:
            proposals[node.id] = {
                "name": node.name,
                "aliases": aliases,
                "ambiguous": name_counts[node.name.lower()] > 1,
            }

    ambiguous = sum(1 for p in proposals.values() if p["ambiguous"])
    print(f"matched {matched}/{len(graph.nodes)} characters; {len(proposals)} have usable aliases")
    print(f"  {ambiguous} of those share a display name with another character and are flagged")
    print(f"unmatched ({len(unmatched)}), first 15: {', '.join(unmatched[:15])}")

    lines = [
        "# SUGGESTIONS ONLY - not read by the build.",
        "#",
        "# Generated by `python -m pipeline.tools.propose_aliases` from",
        "# An API of Ice and Fire <https://anapioficeandfire.com>, maintained by Joakim Skoog.",
        "#",
        "# Review each entry and move the good ones into asoiaf.yaml by hand. The API is",
        "# derived from the wiki and includes show-only naming, so it is a starting point",
        "# rather than an answer. Entries marked AMBIGUOUS share a display name with",
        "# another character and were matched by that name, so at least one of the pair",
        "# is receiving someone else's aliases.",
        "",
        "asoiaf:",
    ]
    for node_id in sorted(proposals):
        proposal = proposals[node_id]
        flag = "  <- AMBIGUOUS, verify" if proposal["ambiguous"] else ""
        lines.append(f"  {node_id}:   # {proposal['name']}{flag}")
        lines.append("    aliases:")
        lines += [f"      - {_scalar(alias)}" for alias in proposal["aliases"]]

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    _assert_parses(OUT)
    print(f"\nwrote {OUT}")
    return 0


def _scalar(value: str) -> str:
    """Aliases contain apostrophes and stray quote marks, which is enough to
    produce a file that looks fine and will not parse."""
    return json.dumps(value, ensure_ascii=False)


def _assert_parses(path: Path) -> None:
    import yaml

    yaml.safe_load(path.read_text(encoding="utf-8"))


if __name__ == "__main__":
    raise SystemExit(main())
